# Architecture identifier.
arch = "aarch64" # str
# Platform identifier.
platform = "aarch64-sel4" # str

#
# Platform configs
#
[plat]
# Platform family.
family = "aarch64-sel4" # str

# Base address of the whole physical memory.
phys-memory-base = 0x4000_0000 # uint
# Size of the whole physical memory. (128M)
phys-memory-size = 0x800_0000 # uint
# Base physical address of the kernel image.
kernel-base-paddr = 0x4020_0000 # uint
# Base virtual address of the kernel image.
kernel-base-vaddr = "0x0000_0000_4020_0000" # uint
# Linear mapping offset, for quick conversions between physical and virtual
# addresses.
phys-virt-offset = "0x0000_0000_0000_0000" # uint
# Offset of bus address and phys address. some boards, the bus address is
# different from the physical address.
phys-bus-offset = 0 # uint
# Kernel address space base.
kernel-aspace-base = "0x0000_0000_0000_0000" # uint
# Kernel address space size.
kernel-aspace-size = "0x0000_ffff_ffff_f000" # uint

#
# Device specifications
#
[devices]
# MMIO regions with format (`base_paddr`, `size`).
mmio-regions = [] # [(uint, uint)]
# VirtIO MMIO regions with format (`base_paddr`, `size`).
virtio-mmio-regions = [] # [(uint, uint)]
# UART Address
uart-paddr = 0x0900_0000 # uint
# UART IRQ number
uart-irq = 1 # uint

# pl031@9010000 {
#     clock-names = "apb_pclk";
#     clocks = <0x8000>;
#     interrupts = <0x00 0x02 0x04>;
#     reg = <0x00 0x9010000 0x00 0x1000>;
#     compatible = "arm,pl031\0arm,primecell";
# };
# RTC (PL031) Address
rtc-paddr = 0x901_0000 # uint
